services:
  web:
    build: .
    command: >
      ./wait-for-it.sh db:5432 -- bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
#      - redis
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:admin@db:5432/sneakers

#  celery:
#    build: .
#    command: celery -A app.celery worker --loglevel=info --pool=solo
#    volumes:
#      - .:/app
#    depends_on:
#      - redis
#    environment:
#      - CELERY_BROKER_URL=redis://redis:6379/0
#      - CELERY_RESULT_BACKEND=redis://redis:6379/0
#    dns:
#      - 8.8.8.8
#      - 1.1.1.1
#
#  redis:
#    image: redis:7
#    ports:
#      - "6379:6379"

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: sneakers
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: