"""add cart model

Revision ID: 8a01f87fe48c
Revises: 3d89db56c03f
Create Date: 2025-05-26 09:17:21.318994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a01f87fe48c'
down_revision: Union[str, None] = '3d89db56c03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_items', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cart_items_user_id'), 'cart_items', ['user_id'], unique=False)
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_index(op.f('ix_cart_items_user_id'), table_name='cart_items')
    op.drop_column('cart_items', 'user_id')
    # ### end Alembic commands ###
