"""add priduct with variant

Revision ID: ee98ed9ad3af
Revises: d851027315b5
Create Date: 2025-06-08 19:32:58.332889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee98ed9ad3af'
down_revision: Union[str, None] = 'd851027315b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=True),
    sa.Column('size', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['variant_id'], ['variant.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('cart_items', sa.Column('size', sa.Float(), nullable=False))
    op.drop_column('variant', 'quantity')
    op.drop_column('variant', 'size')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('variant', sa.Column('size', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('variant', sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('cart_items', 'size')
    op.drop_table('size_info')
    # ### end Alembic commands ###
